"""Download the fonts listed in design/fonts/fonts.toml from Google Fonts.

Writes design/fonts/_aic-*.woff2 (the leading underscore keeps Anki's Check Media
from deleting them), design/fonts/fonts.css with the @font-face rules, and the
licenses. Run: uv run python scripts/fetch_fonts.py
"""

from __future__ import annotations

import re
import tomllib
import urllib.parse
import urllib.request
from pathlib import Path

FONTS_DIR = Path(__file__).resolve().parents[1] / "design" / "fonts"
CSS_API = "https://fonts.googleapis.com/css2"
LICENSES = "https://cdn.jsdelivr.net/npm/@fontsource/{slug}/LICENSE"
# Google Fonts only serves woff2 to a modern browser user agent.
USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"
BLOCK = re.compile(r"/\* (?P<subset>[\w-]+) \*/\s*@font-face \{(?P<body>.*?)\}", re.S)


def get(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read()


def slug(family: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", family.lower()).strip("-")


def main() -> None:
    spec = tomllib.loads((FONTS_DIR / "fonts.toml").read_text())
    subsets = spec["subsets"]
    for old in FONTS_DIR.glob("_aic-*.woff2"):
        old.unlink()
    (FONTS_DIR / "licenses").mkdir(exist_ok=True)

    rules = ["/* Generated by scripts/fetch_fonts.py from fonts.toml. Do not edit. */"]
    for font in spec["font"]:
        family, weights = font["family"], font["weights"]
        query = urllib.parse.urlencode(
            {"family": f"{family}:wght@{';'.join(map(str, weights))}", "display": "swap"}
        )
        css = get(f"{CSS_API}?{query}").decode()
        for block in BLOCK.finditer(css):
            if block["subset"] not in subsets:
                continue
            body = block["body"]
            weight = re.search(r"font-weight: (\d+)", body)[1]
            url = re.search(r"url\((https://[^)]+\.woff2)\)", body)[1]
            unicode_range = re.search(r"unicode-range: ([^;]+);", body)[1]
            name = f"_aic-{slug(family)}-{weight}-{block['subset']}.woff2"
            (FONTS_DIR / name).write_bytes(get(url))
            rules.append(
                f'@font-face {{ font-family: "{family}"; font-weight: {weight}; font-style: normal; '
                f'font-display: block; src: url("{name}") format("woff2"); unicode-range: {unicode_range}; }}'
            )
            print(name)
        (FONTS_DIR / "licenses" / f"{slug(family)}.txt").write_bytes(get(LICENSES.format(slug=slug(family))))
    (FONTS_DIR / "fonts.css").write_text("\n".join(rules) + "\n")


if __name__ == "__main__":
    main()
